version: '3'
services:
  prophet:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prophet:latest
    container_name: prophet
    command: sh -c "python ./index.py -p 5000"
    ports:
      - "5000:5000"
    networks:
      - default

networks:
  default:
    name: fiware_default
    external: true