#Very easy docker-compose file taken from docker-hub
version: "3.5"

services:
    ### Database for Context Broker ###
    mongo-db:
        image: mongo:3.6
        hostname: mongo-db
        container_name: mongo
        expose:
            - "27017"
        ports:
            - 27017:27017
        networks:
            - default
        command: --bind_ip_all --smallfiles

    ### Context Broker ###
    orion-ld:
        image: fiware/orion-ld:latest
        hostname: orion-ld
        container_name: fiware-orion-ld
        depends_on:
            - mongo-db
        networks:
            - default
        ports:
            - 1026:1026
        command:
            -dbhost mongo-db -logLevel DEBUG -corsOrigin __ALL
        restart: always
